import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';
import forecourt from './eslint.rules.mjs';

/**
 * `pnpm lint` had never run: eslint was not installed and there was no config
 * file anywhere in the repository, so the gate CLAUDE.md describes was empty.
 *
 * Started deliberately at the recommended sets rather than a large hand-picked
 * list. A lint config that lands with hundreds of pre-existing violations gets
 * `--max-warnings=9999`-ed on the first CI run and never recovers, so anything
 * stylistic is off and what remains is correctness plus our own rules.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/dist/**',
      'demo/preview/**',    // generated HTML
      'design/**',          // Claude Design canvas exports
      'packages/tokens/**', // the token source itself — see no-raw-hex below
      '**/next-env.d.ts',   // generated by Next on every build
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    plugins: { forecourt },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: { ...globals.node },
    },
    rules: {
      'forecourt/no-raw-hex': 'error',

      // Deliberately relaxed for now, each for a reason rather than to get to
      // green: the codebase parses external provider payloads (`any` at the
      // boundary is honest), and unused args are already caught by tsc.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': ['error', {
        argsIgnorePattern: '^_',
        varsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
      }],
    },
  },

  {
    // Tests assert on shapes that do not always typecheck cleanly by design,
    // and non-null assertions in a fixture are fine.
    files: ['**/*.test.ts', 'tests/**/*.ts'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
    },
  },

  {
    // The renderers emit CSS, which is the one place a hex code is legitimate —
    // but ONLY where it comes from a token. `theme.ts` is the boundary that
    // turns tokens.json into custom properties; everything downstream uses
    // var(--…). Kept as a narrow, named exception rather than a blanket off.
    files: ['apps/site/src/render/theme.ts', 'packages/tokens/**/*.ts'],
    rules: { 'forecourt/no-raw-hex': 'off' },
  },

  {
    // `placeholderImage` generates the stand-in SVG that replaces a dealer's
    // copyrighted photography in the demo. It is artwork, not chrome — a real
    // photograph is not themed either — and it carries its own dark-mode rule
    // because an <img>-embedded SVG cannot see our custom properties. Exempt
    // by name so the rest of the demo data stays covered.
    files: ['demo/kennington.ts', 'demo/build-preview.ts'],
    rules: { 'forecourt/no-raw-hex': 'off' },
  },
);
