-- =====================================================================
-- M19 — Compliance centre.
--
-- Expand-only. Rollback: 0017_compliance.down.sql
-- Depends on 0001_tenancy, 0007_contacts, 0010_deals.
--
-- Compliance is the differentiator, so it gets a front door. Three things
-- here are not administrative tidiness:
--
--   1. EVERY COMPLIANCE STATEMENT CITES ITS SOURCE. §27.4 requires it: a
--      dealer's own adviser must be able to check our interpretation against
--      the FCA Handbook, an HMRC notice or the legislation itself. A rule
--      without a citation is an assertion, and we are not a person who gets to
--      make assertions about somebody else's regulatory position.
--
--   2. TWO CLOCKS START WITHOUT ANYONE PRESSING ANYTHING. A complaint starts
--      the DISP final-response clock the moment it is received; a personal
--      data breach starts a 72-hour clock the moment somebody becomes AWARE of
--      it, which is not the moment it happened. Both are computed from a
--      stored timestamp rather than tracked by hand, because the failure mode
--      is a deadline nobody noticed.
--
--   3. A REGISTER ENTRY THAT HAS EXPIRED IS THE POINT. Trade plates, motor
--      trade insurance, an FCA permission, a member of staff's competence
--      sign-off — the register exists to surface the one that lapsed, so
--      `expires_on` is indexed and a lapse is a query.
-- =====================================================================

BEGIN;

CREATE TYPE register_kind AS ENUM (
  'trade_plate', 'motor_trade_insurance', 'fca_permission', 'appointed_rep_agreement',
  'staff_competence', 'aml_policy', 'aml_risk_assessment', 'dpia',
  'sub_processor', 'trade_body_membership', 'other'
);

CREATE TYPE compliance_task_status AS ENUM ('open', 'in_progress', 'done', 'waived');

-- DISP outcomes, as the Handbook names them.
CREATE TYPE complaint_outcome AS ENUM (
  'upheld', 'partly_upheld', 'not_upheld', 'withdrawn', 'outside_scope'
);

CREATE TYPE complaint_status AS ENUM (
  'received', 'acknowledged', 'investigating', 'final_response_sent', 'closed', 'referred_to_fos'
);

CREATE TYPE breach_status AS ENUM (
  'discovered', 'assessing', 'reported_to_ico', 'not_reportable', 'closed'
);

-- ------------------------------------------------------------ registers
--
-- One table rather than nine near-identical ones. Every register the spec
-- lists has the same shape — a thing with a reference, a holder and an expiry
-- — and nine tables would be nine places to forget the expiry index.
CREATE TABLE compliance_registers (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id),
  site_id         uuid REFERENCES sites(id),

  kind            register_kind NOT NULL,
  reference       text,
  description     text NOT NULL,

  -- Who or what it applies to. A competence record is about a person; a trade
  -- plate is about the business.
  subject_user_id uuid REFERENCES users(id),
  issuer          text,

  valid_from      date,
  expires_on      date,

  -- Where the paperwork lives. M5's storage key, or an external URL.
  document_key    text,
  notes           text,

  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  created_by      uuid REFERENCES users(id),
  updated_by      uuid REFERENCES users(id),

  CONSTRAINT register_description_not_blank CHECK (length(btrim(description)) > 0),
  CONSTRAINT register_dates_ordered CHECK (
    valid_from IS NULL OR expires_on IS NULL OR expires_on >= valid_from
  )
);
-- The query the register exists for: what has lapsed, and what is about to.
CREATE INDEX compliance_registers_expiry_idx
  ON compliance_registers (tenant_id, expires_on)
  WHERE expires_on IS NOT NULL;
CREATE INDEX compliance_registers_kind_idx ON compliance_registers (tenant_id, kind);

-- ---------------------------------------------------------------- tasks
CREATE TABLE compliance_tasks (
  id              uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  tenant_id       uuid NOT NULL REFERENCES tenants(id),

  title           text NOT NULL,
  detail          text,
  status          compliance_task_status NOT NULL DEFAULT 'open',

  due_on          date,
  assigned_to     uuid REFERENCES users(id),

  -- What this task came from, so a dashboard can link back rather than
  -- describing something the user then has to go and find.
  source_kind     text,
  source_id       uuid,

  -- §27.4: every compliance rule links to its source so a dealer's adviser can
  -- verify our interpretation. A task generated by a rule carries the rule's
  -- citation with it.
  citation_ref    text,
  citation_url    text,

  completed_at    timestamptz,
  waived_reason   text,

  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  created_by      uuid REFERENCES users(id),

  CONSTRAINT compliance_task_title_not_blank CHECK (length(btrim(title)) > 0),
  -- Waiving a compliance task is a decision somebody made. Without a reason it
  -- is indistinguishable from the task having been done.
  CONSTRAINT compliance_task_waived_has_reason CHECK (
    status <> 'waived' OR waived_reason IS NOT NULL
  ),
  CONSTRAINT compliance_task_done_has_timestamp CHECK (
    status <> 'done' OR completed_at IS NOT NULL
  )
);
CREATE INDEX compliance_tasks_open_idx ON compliance_tasks (tenant_id, due_on)
  WHERE status IN ('open', 'in_progress');

-- ----------------------------------------------------------- complaints
--
-- DISP. The final-response clock starts when the complaint is RECEIVED, not
-- when somebody gets round to logging it, so `received_at` is what the
-- deadline is computed from and it is deliberately separate from `created_at`.
CREATE TABLE complaints (
  id                  uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  tenant_id           uuid NOT NULL REFERENCES tenants(id),
  contact_id          uuid REFERENCES contacts(id),
  deal_id             uuid REFERENCES deals(id),

  reference           text,
  summary             text NOT NULL,
  status              complaint_status NOT NULL DEFAULT 'received',

  received_at         timestamptz NOT NULL,
  acknowledged_at     timestamptz,
  final_response_at   timestamptz,
  closed_at           timestamptz,

  outcome             complaint_outcome,
  -- Redress actually paid, in minor units like all money here.
  redress_pence       bigint,
  currency            text NOT NULL DEFAULT 'GBP',

  -- Whether the customer was told about the Financial Ombudsman Service. DISP
  -- requires it in the final response, and "we think we mentioned it" is not
  -- a record.
  fos_rights_given    boolean NOT NULL DEFAULT false,
  referred_to_fos_at  timestamptz,

  root_cause          text,
  notes               text,

  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  created_by          uuid REFERENCES users(id),

  CONSTRAINT complaint_summary_not_blank CHECK (length(btrim(summary)) > 0),
  CONSTRAINT complaint_redress_non_negative CHECK (
    redress_pence IS NULL OR redress_pence >= 0
  ),
  -- A final response is where the FOS rights are given. Recording one without
  -- them is recording a response that did not comply.
  CONSTRAINT complaint_final_response_gives_fos_rights CHECK (
    final_response_at IS NULL OR fos_rights_given
  ),
  CONSTRAINT complaint_final_response_has_outcome CHECK (
    final_response_at IS NULL OR outcome IS NOT NULL
  ),
  CONSTRAINT complaint_dates_ordered CHECK (
    final_response_at IS NULL OR final_response_at >= received_at
  )
);
CREATE INDEX complaints_open_idx ON complaints (tenant_id, received_at)
  WHERE status NOT IN ('closed', 'referred_to_fos');

-- ------------------------------------------------------------- breaches
--
-- UK GDPR Article 33: the ICO must be told within 72 hours of BECOMING AWARE,
-- which is not the moment the breach happened and frequently not the same day.
-- Both timestamps are stored because the gap between them is itself something
-- a regulator asks about.
CREATE TABLE data_breaches (
  id                    uuid PRIMARY KEY DEFAULT uuid_generate_v7(),
  tenant_id             uuid NOT NULL REFERENCES tenants(id),

  summary               text NOT NULL,
  status                breach_status NOT NULL DEFAULT 'discovered',

  occurred_at           timestamptz,
  -- The one the 72-hour clock runs from.
  became_aware_at       timestamptz NOT NULL,

  reported_to_ico_at    timestamptz,
  ico_reference         text,
  -- Article 33(1) permits not reporting where the breach is unlikely to
  -- result in a risk to rights and freedoms. That is a decision with a
  -- justification, never a silence.
  not_reportable_reason text,

  -- Article 34: tell the data subjects too where the risk is high.
  subjects_notified_at  timestamptz,
  subjects_affected     integer,

  containment           text,
  root_cause            text,

  created_at            timestamptz NOT NULL DEFAULT now(),
  updated_at            timestamptz NOT NULL DEFAULT now(),
  created_by            uuid REFERENCES users(id),

  CONSTRAINT breach_summary_not_blank CHECK (length(btrim(summary)) > 0),
  CONSTRAINT breach_subjects_non_negative CHECK (
    subjects_affected IS NULL OR subjects_affected >= 0
  ),
  -- Deciding not to report is a decision with a reason attached to it.
  CONSTRAINT breach_not_reportable_has_reason CHECK (
    status <> 'not_reportable' OR not_reportable_reason IS NOT NULL
  ),
  CONSTRAINT breach_reported_has_timestamp CHECK (
    status <> 'reported_to_ico' OR reported_to_ico_at IS NOT NULL
  ),
  CONSTRAINT breach_aware_after_occurred CHECK (
    occurred_at IS NULL OR became_aware_at >= occurred_at
  )
);
CREATE INDEX data_breaches_open_idx ON data_breaches (tenant_id, became_aware_at DESC)
  WHERE status IN ('discovered', 'assessing');

SELECT * FROM apply_tenant_policies();

COMMIT;
